services:
  - type: web
    name: shift-scheduler
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: AUTO_INIT_DB
        value: "true"
      - key: STORAGE_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        sync: false
      - key: DB_SSL_VERIFY_CERT
        value: "true"
      - key: DATABASE_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_SSL_CA
        sync: false
